[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit.remote.link }}/commit/{{ commit.id }}))\
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
filter_commits = true
tag_pattern = ".*"
sort_commits = "newest"

commit_parsers = [
  { message = "^feat", group = "ğŸš€ Features" },
  { message = "^fix", group = "ğŸ› Bug Fixes" },
  { message = "^perf", group = "âš¡ Performance" },
  { message = "^revert", group = "â—€ï¸ Reverts" },
  { message = "^chore", skip = true },
  { message = "^ci", skip = true },
  { message = "^docs", skip = true },
  { message = "^refactor", skip = true },
  { message = "^style", skip = true },
  { message = "^build", skip = true },
  { message = "^test", skip = true },
]
